// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App404: typeof import('./../views/App404.vue')['default']
    AppHome: typeof import('./../views/AppHome.vue')['default']
    AppInput: typeof import('./../components/forms/AppInput.vue')['default']
    AppModal: typeof import('./../components/AppModal.vue')['default']
    AppNavbar: typeof import('./../components/AppNavbar.vue')['default']
    AppNestedMenu: typeof import('./../components/nested-menu/AppNestedMenu.vue')['default']
    AppNestedMenuChildren: typeof import('./../components/nested-menu/AppNestedMenuChildren.vue')['default']
    AppSaveButton: typeof import('./../components/AppSaveButton.vue')['default']
    AppSelect: typeof import('./../components/forms/AppSelect.vue')['default']
    AppSidebar: typeof import('./../components/AppSidebar.vue')['default']
    LayoutSidebar: typeof import('./../layouts/LayoutSidebar.vue')['default']
  }
}

export { }
