// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppModal: typeof import('./../components/AppModal.vue')['default']
    AppNavbar: typeof import('./../components/AppNavbar.vue')['default']
    AppSaveButton: typeof import('./../components/AppSaveButton.vue')['default']
    PageSettingsModalBlueprint: typeof import('./../../posts/components/settings/PageSettingsModalBlueprint.vue')['default']
    PageSettingsModalGeneral: typeof import('./../../posts/components/settings/PageSettingsModalGeneral.vue')['default']
    PageSettingsModalSearch: typeof import('./../../posts/components/settings/PageSettingsModalSearch.vue')['default']
    PageSettingsModalSocialMedia: typeof import('./../../posts/components/settings/PageSettingsModalSocialMedia.vue')['default']
    PostSettingsModal: typeof import('./../../posts/components/settings/PostSettingsModal.vue')['default']
  }
}

export { }
